//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.WesternUnionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PullRemittanceRequest", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class PullRemittanceRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.LookupTransactionRequest LookupTransactionRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.PayoutTransactionRequest PayoutTransactionRequestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PullMethodField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.LookupTransactionRequest LookupTransactionRequest {
            get {
                return this.LookupTransactionRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.LookupTransactionRequestField, value) != true)) {
                    this.LookupTransactionRequestField = value;
                    this.RaisePropertyChanged("LookupTransactionRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.PayoutTransactionRequest PayoutTransactionRequest {
            get {
                return this.PayoutTransactionRequestField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutTransactionRequestField, value) != true)) {
                    this.PayoutTransactionRequestField = value;
                    this.RaisePropertyChanged("PayoutTransactionRequest");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PullMethod {
            get {
                return this.PullMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PullMethodField, value) != true)) {
                    this.PullMethodField = value;
                    this.RaisePropertyChanged("PullMethod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class LookupTransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.CebuanaBranchInformation CebuanaBranchInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.CebuanaBranchInformation CebuanaBranchInformation {
            get {
                return this.CebuanaBranchInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CebuanaBranchInformationField, value) != true)) {
                    this.CebuanaBranchInformationField = value;
                    this.RaisePropertyChanged("CebuanaBranchInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCurrency {
            get {
                return this.PayoutCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCurrencyField, value) != true)) {
                    this.PayoutCurrencyField = value;
                    this.RaisePropertyChanged("PayoutCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNumberField, value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayoutTransactionRequest", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class PayoutTransactionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.CebuanaBranchInformation CebuanaBranchInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurrencyConversionRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerInternalNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayTokenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PayoutAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PayoutAmountWithServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverCustomerNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverIDCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverIDExpiryDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverIDIssuedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverIDNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverIDTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderMobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendingCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryPhoneNumber {
            get {
                return this.BeneficiaryPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryPhoneNumberField, value) != true)) {
                    this.BeneficiaryPhoneNumberField = value;
                    this.RaisePropertyChanged("BeneficiaryPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.CebuanaBranchInformation CebuanaBranchInformation {
            get {
                return this.CebuanaBranchInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.CebuanaBranchInformationField, value) != true)) {
                    this.CebuanaBranchInformationField = value;
                    this.RaisePropertyChanged("CebuanaBranchInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrencyConversionRate {
            get {
                return this.CurrencyConversionRateField;
            }
            set {
                if ((this.CurrencyConversionRateField.Equals(value) != true)) {
                    this.CurrencyConversionRateField = value;
                    this.RaisePropertyChanged("CurrencyConversionRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerInternalNumber {
            get {
                return this.PartnerInternalNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerInternalNumberField, value) != true)) {
                    this.PartnerInternalNumberField = value;
                    this.RaisePropertyChanged("PartnerInternalNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayTokenID {
            get {
                return this.PayTokenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayTokenIDField, value) != true)) {
                    this.PayTokenIDField = value;
                    this.RaisePropertyChanged("PayTokenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayoutAmount {
            get {
                return this.PayoutAmountField;
            }
            set {
                if ((this.PayoutAmountField.Equals(value) != true)) {
                    this.PayoutAmountField = value;
                    this.RaisePropertyChanged("PayoutAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayoutAmountWithServiceCharge {
            get {
                return this.PayoutAmountWithServiceChargeField;
            }
            set {
                if ((this.PayoutAmountWithServiceChargeField.Equals(value) != true)) {
                    this.PayoutAmountWithServiceChargeField = value;
                    this.RaisePropertyChanged("PayoutAmountWithServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCountry {
            get {
                return this.PayoutCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCountryField, value) != true)) {
                    this.PayoutCountryField = value;
                    this.RaisePropertyChanged("PayoutCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCurrency {
            get {
                return this.PayoutCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCurrencyField, value) != true)) {
                    this.PayoutCurrencyField = value;
                    this.RaisePropertyChanged("PayoutCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutID {
            get {
                return this.PayoutIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutIDField, value) != true)) {
                    this.PayoutIDField = value;
                    this.RaisePropertyChanged("PayoutID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverCity {
            get {
                return this.ReceiverCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverCityField, value) != true)) {
                    this.ReceiverCityField = value;
                    this.RaisePropertyChanged("ReceiverCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverCountry {
            get {
                return this.ReceiverCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverCountryField, value) != true)) {
                    this.ReceiverCountryField = value;
                    this.RaisePropertyChanged("ReceiverCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverCustomerNumber {
            get {
                return this.ReceiverCustomerNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverCustomerNumberField, value) != true)) {
                    this.ReceiverCustomerNumberField = value;
                    this.RaisePropertyChanged("ReceiverCustomerNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFirstName {
            get {
                return this.ReceiverFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFirstNameField, value) != true)) {
                    this.ReceiverFirstNameField = value;
                    this.RaisePropertyChanged("ReceiverFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverFullName {
            get {
                return this.ReceiverFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFullNameField, value) != true)) {
                    this.ReceiverFullNameField = value;
                    this.RaisePropertyChanged("ReceiverFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverIDCode {
            get {
                return this.ReceiverIDCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDCodeField, value) != true)) {
                    this.ReceiverIDCodeField = value;
                    this.RaisePropertyChanged("ReceiverIDCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverIDExpiryDate {
            get {
                return this.ReceiverIDExpiryDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDExpiryDateField, value) != true)) {
                    this.ReceiverIDExpiryDateField = value;
                    this.RaisePropertyChanged("ReceiverIDExpiryDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverIDIssuedDate {
            get {
                return this.ReceiverIDIssuedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDIssuedDateField, value) != true)) {
                    this.ReceiverIDIssuedDateField = value;
                    this.RaisePropertyChanged("ReceiverIDIssuedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverIDNumber {
            get {
                return this.ReceiverIDNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDNumberField, value) != true)) {
                    this.ReceiverIDNumberField = value;
                    this.RaisePropertyChanged("ReceiverIDNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverIDType {
            get {
                return this.ReceiverIDTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverIDTypeField, value) != true)) {
                    this.ReceiverIDTypeField = value;
                    this.RaisePropertyChanged("ReceiverIDType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReceiverLastName {
            get {
                return this.ReceiverLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverLastNameField, value) != true)) {
                    this.ReceiverLastNameField = value;
                    this.RaisePropertyChanged("ReceiverLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderCountry {
            get {
                return this.SenderCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderCountryField, value) != true)) {
                    this.SenderCountryField = value;
                    this.RaisePropertyChanged("SenderCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmail {
            get {
                return this.SenderEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEmailField, value) != true)) {
                    this.SenderEmailField = value;
                    this.RaisePropertyChanged("SenderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFirstName {
            get {
                return this.SenderFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFirstNameField, value) != true)) {
                    this.SenderFirstNameField = value;
                    this.RaisePropertyChanged("SenderFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFullName {
            get {
                return this.SenderFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFullNameField, value) != true)) {
                    this.SenderFullNameField = value;
                    this.RaisePropertyChanged("SenderFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderID {
            get {
                return this.SenderIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderIDField, value) != true)) {
                    this.SenderIDField = value;
                    this.RaisePropertyChanged("SenderID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderLastName {
            get {
                return this.SenderLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderLastNameField, value) != true)) {
                    this.SenderLastNameField = value;
                    this.RaisePropertyChanged("SenderLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderMobileNumber {
            get {
                return this.SenderMobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderMobileNumberField, value) != true)) {
                    this.SenderMobileNumberField = value;
                    this.RaisePropertyChanged("SenderMobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderState {
            get {
                return this.SenderStateField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderStateField, value) != true)) {
                    this.SenderStateField = value;
                    this.RaisePropertyChanged("SenderState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendingCurrency {
            get {
                return this.SendingCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.SendingCurrencyField, value) != true)) {
                    this.SendingCurrencyField = value;
                    this.RaisePropertyChanged("SendingCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNumberField, value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CebuanaBranchInformation", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class CebuanaBranchInformation : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchRegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchUserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientApplicationVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClientMacAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchAreaCode {
            get {
                return this.BranchAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchAreaCodeField, value) != true)) {
                    this.BranchAreaCodeField = value;
                    this.RaisePropertyChanged("BranchAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchRegionCode {
            get {
                return this.BranchRegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchRegionCodeField, value) != true)) {
                    this.BranchRegionCodeField = value;
                    this.RaisePropertyChanged("BranchRegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchUserID {
            get {
                return this.BranchUserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchUserIDField, value) != true)) {
                    this.BranchUserIDField = value;
                    this.RaisePropertyChanged("BranchUserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientApplicationVersion {
            get {
                return this.ClientApplicationVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientApplicationVersionField, value) != true)) {
                    this.ClientApplicationVersionField = value;
                    this.RaisePropertyChanged("ClientApplicationVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientMacAddress {
            get {
                return this.ClientMacAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.ClientMacAddressField, value) != true)) {
                    this.ClientMacAddressField = value;
                    this.RaisePropertyChanged("ClientMacAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PullRemittanceResult", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class PullRemittanceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.LookupTransactionResult LookupTransactionResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.PayoutTransactionResult PayoutTransactionResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PullMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.LookupCustomerResult UnlockTransactionResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.LookupTransactionResult LookupTransactionResult {
            get {
                return this.LookupTransactionResultField;
            }
            set {
                if ((object.ReferenceEquals(this.LookupTransactionResultField, value) != true)) {
                    this.LookupTransactionResultField = value;
                    this.RaisePropertyChanged("LookupTransactionResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.PayoutTransactionResult PayoutTransactionResult {
            get {
                return this.PayoutTransactionResultField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutTransactionResultField, value) != true)) {
                    this.PayoutTransactionResultField = value;
                    this.RaisePropertyChanged("PayoutTransactionResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PullMethod {
            get {
                return this.PullMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.PullMethodField, value) != true)) {
                    this.PullMethodField = value;
                    this.RaisePropertyChanged("PullMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.LookupCustomerResult UnlockTransactionResult {
            get {
                return this.UnlockTransactionResultField;
            }
            set {
                if ((object.ReferenceEquals(this.UnlockTransactionResultField, value) != true)) {
                    this.UnlockTransactionResultField = value;
                    this.RaisePropertyChanged("UnlockTransactionResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupTransactionResult", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class LookupTransactionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BeneficiaryPhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CurrencyConversionRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageToClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageToClientFromSenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MultiCurrencyPayoutCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayTokenIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PayoutAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PayoutAmountWithServiceChargeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PayoutIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.LookupTransactionResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderMobileNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendingCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SendingCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusFromPartnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TransactionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.TransactionStatus TransactionStatusField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryFirstName {
            get {
                return this.BeneficiaryFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryFirstNameField, value) != true)) {
                    this.BeneficiaryFirstNameField = value;
                    this.RaisePropertyChanged("BeneficiaryFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryFullName {
            get {
                return this.BeneficiaryFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryFullNameField, value) != true)) {
                    this.BeneficiaryFullNameField = value;
                    this.RaisePropertyChanged("BeneficiaryFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryLastName {
            get {
                return this.BeneficiaryLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryLastNameField, value) != true)) {
                    this.BeneficiaryLastNameField = value;
                    this.RaisePropertyChanged("BeneficiaryLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BeneficiaryPhoneNumber {
            get {
                return this.BeneficiaryPhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.BeneficiaryPhoneNumberField, value) != true)) {
                    this.BeneficiaryPhoneNumberField = value;
                    this.RaisePropertyChanged("BeneficiaryPhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CurrencyConversionRate {
            get {
                return this.CurrencyConversionRateField;
            }
            set {
                if ((this.CurrencyConversionRateField.Equals(value) != true)) {
                    this.CurrencyConversionRateField = value;
                    this.RaisePropertyChanged("CurrencyConversionRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageToClient {
            get {
                return this.MessageToClientField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageToClientField, value) != true)) {
                    this.MessageToClientField = value;
                    this.RaisePropertyChanged("MessageToClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageToClientFromSender {
            get {
                return this.MessageToClientFromSenderField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageToClientFromSenderField, value) != true)) {
                    this.MessageToClientFromSenderField = value;
                    this.RaisePropertyChanged("MessageToClientFromSender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MultiCurrencyPayoutCode {
            get {
                return this.MultiCurrencyPayoutCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.MultiCurrencyPayoutCodeField, value) != true)) {
                    this.MultiCurrencyPayoutCodeField = value;
                    this.RaisePropertyChanged("MultiCurrencyPayoutCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginCurrency {
            get {
                return this.OriginCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginCurrencyField, value) != true)) {
                    this.OriginCurrencyField = value;
                    this.RaisePropertyChanged("OriginCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayTokenID {
            get {
                return this.PayTokenIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayTokenIDField, value) != true)) {
                    this.PayTokenIDField = value;
                    this.RaisePropertyChanged("PayTokenID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayoutAmount {
            get {
                return this.PayoutAmountField;
            }
            set {
                if ((this.PayoutAmountField.Equals(value) != true)) {
                    this.PayoutAmountField = value;
                    this.RaisePropertyChanged("PayoutAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayoutAmountWithServiceCharge {
            get {
                return this.PayoutAmountWithServiceChargeField;
            }
            set {
                if ((this.PayoutAmountWithServiceChargeField.Equals(value) != true)) {
                    this.PayoutAmountWithServiceChargeField = value;
                    this.RaisePropertyChanged("PayoutAmountWithServiceCharge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCountry {
            get {
                return this.PayoutCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCountryField, value) != true)) {
                    this.PayoutCountryField = value;
                    this.RaisePropertyChanged("PayoutCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutCurrency {
            get {
                return this.PayoutCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutCurrencyField, value) != true)) {
                    this.PayoutCurrencyField = value;
                    this.RaisePropertyChanged("PayoutCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PayoutID {
            get {
                return this.PayoutIDField;
            }
            set {
                if ((object.ReferenceEquals(this.PayoutIDField, value) != true)) {
                    this.PayoutIDField = value;
                    this.RaisePropertyChanged("PayoutID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.LookupTransactionResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderCountry {
            get {
                return this.SenderCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderCountryField, value) != true)) {
                    this.SenderCountryField = value;
                    this.RaisePropertyChanged("SenderCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderEmail {
            get {
                return this.SenderEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderEmailField, value) != true)) {
                    this.SenderEmailField = value;
                    this.RaisePropertyChanged("SenderEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFirstName {
            get {
                return this.SenderFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFirstNameField, value) != true)) {
                    this.SenderFirstNameField = value;
                    this.RaisePropertyChanged("SenderFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderFullName {
            get {
                return this.SenderFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderFullNameField, value) != true)) {
                    this.SenderFullNameField = value;
                    this.RaisePropertyChanged("SenderFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderLastName {
            get {
                return this.SenderLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderLastNameField, value) != true)) {
                    this.SenderLastNameField = value;
                    this.RaisePropertyChanged("SenderLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderMobileNumber {
            get {
                return this.SenderMobileNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderMobileNumberField, value) != true)) {
                    this.SenderMobileNumberField = value;
                    this.RaisePropertyChanged("SenderMobileNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SenderState {
            get {
                return this.SenderStateField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderStateField, value) != true)) {
                    this.SenderStateField = value;
                    this.RaisePropertyChanged("SenderState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendingCountry {
            get {
                return this.SendingCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.SendingCountryField, value) != true)) {
                    this.SendingCountryField = value;
                    this.RaisePropertyChanged("SendingCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SendingCurrency {
            get {
                return this.SendingCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.SendingCurrencyField, value) != true)) {
                    this.SendingCurrencyField = value;
                    this.RaisePropertyChanged("SendingCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusFromPartner {
            get {
                return this.StatusFromPartnerField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusFromPartnerField, value) != true)) {
                    this.StatusFromPartnerField = value;
                    this.RaisePropertyChanged("StatusFromPartner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TransactionDate {
            get {
                return this.TransactionDateField;
            }
            set {
                if ((this.TransactionDateField.Equals(value) != true)) {
                    this.TransactionDateField = value;
                    this.RaisePropertyChanged("TransactionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNumberField, value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.TransactionStatus TransactionStatus {
            get {
                return this.TransactionStatusField;
            }
            set {
                if ((this.TransactionStatusField.Equals(value) != true)) {
                    this.TransactionStatusField = value;
                    this.RaisePropertyChanged("TransactionStatus");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayoutTransactionResult", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class PayoutTransactionResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageToClientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PayoutDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ClientApplication.WesternUnionService.PayoutTransactionResultCode ResultCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TransactionNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageToClient {
            get {
                return this.MessageToClientField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageToClientField, value) != true)) {
                    this.MessageToClientField = value;
                    this.RaisePropertyChanged("MessageToClient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PayoutDate {
            get {
                return this.PayoutDateField;
            }
            set {
                if ((this.PayoutDateField.Equals(value) != true)) {
                    this.PayoutDateField = value;
                    this.RaisePropertyChanged("PayoutDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ClientApplication.WesternUnionService.PayoutTransactionResultCode ResultCode {
            get {
                return this.ResultCodeField;
            }
            set {
                if ((this.ResultCodeField.Equals(value) != true)) {
                    this.ResultCodeField = value;
                    this.RaisePropertyChanged("ResultCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TransactionNumber {
            get {
                return this.TransactionNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.TransactionNumberField, value) != true)) {
                    this.TransactionNumberField = value;
                    this.RaisePropertyChanged("TransactionNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupCustomerResult", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService.Classes")]
    [System.SerializableAttribute()]
    public partial class LookupCustomerResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AgentSessionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnlockResultCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgentSessionID {
            get {
                return this.AgentSessionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.AgentSessionIDField, value) != true)) {
                    this.AgentSessionIDField = value;
                    this.RaisePropertyChanged("AgentSessionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnlockResultCode {
            get {
                return this.UnlockResultCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UnlockResultCodeField, value) != true)) {
                    this.UnlockResultCodeField = value;
                    this.RaisePropertyChanged("UnlockResultCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LookupTransactionResultCode", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum LookupTransactionResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnrecognizedResponse = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unsuccessful = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartnerError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerError = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum TransactionStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnrecognizedStatus = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ForPayout = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Blocked = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaidOut = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cancelled = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ProcessedForPayout = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PayoutTransactionResultCode", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum PayoutTransactionResultCode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UnrecognizedResponse = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Successful = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unsuccessful = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PartnerError = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ServerError = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GenerateTokenParameters", Namespace="http://schemas.datacontract.org/2004/07/WesternUnionWCFService")]
    [System.SerializableAttribute()]
    public partial class GenerateTokenParameters : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartnerCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReferenceNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecretKeyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((object.ReferenceEquals(this.DateTimeField, value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartnerCode {
            get {
                return this.PartnerCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PartnerCodeField, value) != true)) {
                    this.PartnerCodeField = value;
                    this.RaisePropertyChanged("PartnerCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReferenceNumber {
            get {
                return this.ReferenceNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReferenceNumberField, value) != true)) {
                    this.ReferenceNumberField = value;
                    this.RaisePropertyChanged("ReferenceNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecretKey {
            get {
                return this.SecretKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.SecretKeyField, value) != true)) {
                    this.SecretKeyField = value;
                    this.RaisePropertyChanged("SecretKey");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WesternUnionService.IWesternUnionWCF")]
    public interface IWesternUnionWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWesternUnionWCF/RemittancePartnerLookup", ReplyAction="http://tempuri.org/IWesternUnionWCF/RemittancePartnerLookupResponse")]
        ClientApplication.WesternUnionService.PullRemittanceResult RemittancePartnerLookup(ClientApplication.WesternUnionService.PullRemittanceRequest pullTransactionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWesternUnionWCF/RemittancePartnerPayout", ReplyAction="http://tempuri.org/IWesternUnionWCF/RemittancePartnerPayoutResponse")]
        ClientApplication.WesternUnionService.PullRemittanceResult RemittancePartnerPayout(ClientApplication.WesternUnionService.PullRemittanceRequest pullTransactionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWesternUnionWCF/GenerateToken", ReplyAction="http://tempuri.org/IWesternUnionWCF/GenerateTokenResponse")]
        string GenerateToken(ClientApplication.WesternUnionService.GenerateTokenParameters generateTokenParameters);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWesternUnionWCFChannel : ClientApplication.WesternUnionService.IWesternUnionWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WesternUnionWCFClient : System.ServiceModel.ClientBase<ClientApplication.WesternUnionService.IWesternUnionWCF>, ClientApplication.WesternUnionService.IWesternUnionWCF {
        
        public WesternUnionWCFClient() {
        }
        
        public WesternUnionWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WesternUnionWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WesternUnionWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WesternUnionWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientApplication.WesternUnionService.PullRemittanceResult RemittancePartnerLookup(ClientApplication.WesternUnionService.PullRemittanceRequest pullTransactionRequest) {
            return base.Channel.RemittancePartnerLookup(pullTransactionRequest);
        }
        
        public ClientApplication.WesternUnionService.PullRemittanceResult RemittancePartnerPayout(ClientApplication.WesternUnionService.PullRemittanceRequest pullTransactionRequest) {
            return base.Channel.RemittancePartnerPayout(pullTransactionRequest);
        }
        
        public string GenerateToken(ClientApplication.WesternUnionService.GenerateTokenParameters generateTokenParameters) {
            return base.Channel.GenerateToken(generateTokenParameters);
        }
    }
}
