//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientApplication.ITransFastServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ITransFastServices.ITransFastWCF")]
    public interface ITransFastWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransFastWCF/RemittancePartnerLookup", ReplyAction="http://tempuri.org/ITransFastWCF/RemittancePartnerLookupResponse")]
        TransFastWCFService.Classes.PullRemittanceResult RemittancePartnerLookup(TransFastWCFService.Classes.PullRemittanceRequest pullTransactionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransFastWCF/RemittancePartnerPayout", ReplyAction="http://tempuri.org/ITransFastWCF/RemittancePartnerPayoutResponse")]
        TransFastWCFService.Classes.PullRemittanceResult RemittancePartnerPayout(TransFastWCFService.Classes.PullRemittanceRequest pullTransactionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransFastWCF/GenerateToken", ReplyAction="http://tempuri.org/ITransFastWCF/GenerateTokenResponse")]
        string GenerateToken(TransFastWCFService.GenerateTokenParameters generateTokenParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITransFastWCF/RequestToken", ReplyAction="http://tempuri.org/ITransFastWCF/RequestTokenResponse")]
        TransFastWCFService.Classes.DataTransactionResult RequestToken(TransFastWCFService.Classes.DataTransactionResult dataTransactionResult);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITransFastWCFChannel : ClientApplication.ITransFastServices.ITransFastWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TransFastWCFClient : System.ServiceModel.ClientBase<ClientApplication.ITransFastServices.ITransFastWCF>, ClientApplication.ITransFastServices.ITransFastWCF {
        
        public TransFastWCFClient() {
        }
        
        public TransFastWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TransFastWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransFastWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TransFastWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TransFastWCFService.Classes.PullRemittanceResult RemittancePartnerLookup(TransFastWCFService.Classes.PullRemittanceRequest pullTransactionRequest) {
            return base.Channel.RemittancePartnerLookup(pullTransactionRequest);
        }
        
        public TransFastWCFService.Classes.PullRemittanceResult RemittancePartnerPayout(TransFastWCFService.Classes.PullRemittanceRequest pullTransactionRequest) {
            return base.Channel.RemittancePartnerPayout(pullTransactionRequest);
        }
        
        public string GenerateToken(TransFastWCFService.GenerateTokenParameters generateTokenParameters) {
            return base.Channel.GenerateToken(generateTokenParameters);
        }
        
        public TransFastWCFService.Classes.DataTransactionResult RequestToken(TransFastWCFService.Classes.DataTransactionResult dataTransactionResult) {
            return base.Channel.RequestToken(dataTransactionResult);
        }
    }
}
