//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TransFastWCF.TransFastWebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityAuth", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class EntityAuth : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TransFastWCF.TransFastWebService.EntityType EntityTypeField;
        
        private int EntityCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntityPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TerminalIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TransFastWCF.TransFastWebService.EntityType EntityType {
            get {
                return this.EntityTypeField;
            }
            set {
                if ((this.EntityTypeField.Equals(value) != true)) {
                    this.EntityTypeField = value;
                    this.RaisePropertyChanged("EntityType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int EntityCode {
            get {
                return this.EntityCodeField;
            }
            set {
                if ((this.EntityCodeField.Equals(value) != true)) {
                    this.EntityCodeField = value;
                    this.RaisePropertyChanged("EntityCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string EntityLogin {
            get {
                return this.EntityLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityLoginField, value) != true)) {
                    this.EntityLoginField = value;
                    this.RaisePropertyChanged("EntityLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string EntityPass {
            get {
                return this.EntityPassField;
            }
            set {
                if ((object.ReferenceEquals(this.EntityPassField, value) != true)) {
                    this.EntityPassField = value;
                    this.RaisePropertyChanged("EntityPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TerminalID {
            get {
                return this.TerminalIDField;
            }
            set {
                if ((object.ReferenceEquals(this.TerminalIDField, value) != true)) {
                    this.TerminalIDField = value;
                    this.RaisePropertyChanged("TerminalID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntityType", Namespace="http://www.legionelite.com/")]
    public enum EntityType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Remitentes = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Destinatarios = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Giros = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Agentes = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Corresponsales = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dominios = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PBC = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Caja = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Liquidaciones = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PaisesTarifas = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cuentas_Corresponsales = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cobros = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Orden_de_pago = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Usuarios = 13,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorizationResponse", Namespace="COM")]
    [System.SerializableAttribute()]
    public partial class AutorizationResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TransFastWCF.TransFastWebService.ReturnResult ReturnResultField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TransFastWCF.TransFastWebService.ReturnResult ReturnResult {
            get {
                return this.ReturnResultField;
            }
            set {
                if ((this.ReturnResultField.Equals(value) != true)) {
                    this.ReturnResultField = value;
                    this.RaisePropertyChanged("ReturnResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReturnDescription {
            get {
                return this.ReturnDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDescriptionField, value) != true)) {
                    this.ReturnDescriptionField = value;
                    this.RaisePropertyChanged("ReturnDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReturnToken {
            get {
                return this.ReturnTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnTokenField, value) != true)) {
                    this.ReturnTokenField = value;
                    this.RaisePropertyChanged("ReturnToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResult", Namespace="COM")]
    public enum ReturnResult : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoData = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MTO_InfoRequest", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class MTO_InfoRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTermField;
        
        private TransFastWCF.TransFastWebService.SearchPayMode SearchTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SearchTerm {
            get {
                return this.SearchTermField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTermField, value) != true)) {
                    this.SearchTermField = value;
                    this.RaisePropertyChanged("SearchTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public TransFastWCF.TransFastWebService.SearchPayMode SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((this.SearchTypeField.Equals(value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SearchPayMode", Namespace="http://www.legionelite.com/")]
    public enum SearchPayMode : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PinNumber = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperationNumber = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CorrespondentReference = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LID = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MTO_InfoResponse", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class MTO_InfoResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TransFastWCF.TransFastWebService.ReturnResult1 ReturnResultField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransFastWCF.TransFastWebService.InvoiceData InvoiceDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TransFastWCF.TransFastWebService.ReturnResult1 ReturnResult {
            get {
                return this.ReturnResultField;
            }
            set {
                if ((this.ReturnResultField.Equals(value) != true)) {
                    this.ReturnResultField = value;
                    this.RaisePropertyChanged("ReturnResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReturnDescription {
            get {
                return this.ReturnDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDescriptionField, value) != true)) {
                    this.ReturnDescriptionField = value;
                    this.RaisePropertyChanged("ReturnDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public TransFastWCF.TransFastWebService.InvoiceData InvoiceData {
            get {
                return this.InvoiceDataField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceDataField, value) != true)) {
                    this.InvoiceDataField = value;
                    this.RaisePropertyChanged("InvoiceData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceData", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class InvoiceData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderCountryOfBirthField;
        
        private System.DateTime SenderdateOfBirthField;
        
        private TransFastWCF.TransFastWebService.Sex SenderSexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransFastWCF.TransFastWebService.DocumentData SenderDocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAdressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverAdressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverPhone1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverPhone2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransFastWCF.TransFastWebService.DocumentData ReceiverDocumentField;
        
        private System.DateTime ReceiverDOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransFastWCF.TransFastWebService.BankAccout BankAccountField;
        
        private TransFastWCF.TransFastWebService.ModeOfPayment PaymentMethodField;
        
        private int InvoiceConsecutiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoicePinField;
        
        private int InvoiceInternalIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceMessageField;
        
        private double InvoiceAmmountToReceiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceCurrencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InvoiceExchangeRateField;
        
        private bool ReadyForPayField;
        
        private TransFastWCF.TransFastWebService.InvoiceStatus InvoiceStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private TransFastWCF.TransFastWebService.AditionalData InvoiceAditionalDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string SenderName {
            get {
                return this.SenderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderNameField, value) != true)) {
                    this.SenderNameField = value;
                    this.RaisePropertyChanged("SenderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SenderLastName {
            get {
                return this.SenderLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderLastNameField, value) != true)) {
                    this.SenderLastNameField = value;
                    this.RaisePropertyChanged("SenderLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderCountry {
            get {
                return this.SenderCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderCountryField, value) != true)) {
                    this.SenderCountryField = value;
                    this.RaisePropertyChanged("SenderCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SenderCountryOfBirth {
            get {
                return this.SenderCountryOfBirthField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderCountryOfBirthField, value) != true)) {
                    this.SenderCountryOfBirthField = value;
                    this.RaisePropertyChanged("SenderCountryOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime SenderdateOfBirth {
            get {
                return this.SenderdateOfBirthField;
            }
            set {
                if ((this.SenderdateOfBirthField.Equals(value) != true)) {
                    this.SenderdateOfBirthField = value;
                    this.RaisePropertyChanged("SenderdateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public TransFastWCF.TransFastWebService.Sex SenderSex {
            get {
                return this.SenderSexField;
            }
            set {
                if ((this.SenderSexField.Equals(value) != true)) {
                    this.SenderSexField = value;
                    this.RaisePropertyChanged("SenderSex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string SenderCity {
            get {
                return this.SenderCityField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderCityField, value) != true)) {
                    this.SenderCityField = value;
                    this.RaisePropertyChanged("SenderCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string SenderProvince {
            get {
                return this.SenderProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderProvinceField, value) != true)) {
                    this.SenderProvinceField = value;
                    this.RaisePropertyChanged("SenderProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string SenderPhone {
            get {
                return this.SenderPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderPhoneField, value) != true)) {
                    this.SenderPhoneField = value;
                    this.RaisePropertyChanged("SenderPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public TransFastWCF.TransFastWebService.DocumentData SenderDocument {
            get {
                return this.SenderDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderDocumentField, value) != true)) {
                    this.SenderDocumentField = value;
                    this.RaisePropertyChanged("SenderDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string ReceiverName {
            get {
                return this.ReceiverNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverNameField, value) != true)) {
                    this.ReceiverNameField = value;
                    this.RaisePropertyChanged("ReceiverName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string ReceiverLastName {
            get {
                return this.ReceiverLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverLastNameField, value) != true)) {
                    this.ReceiverLastNameField = value;
                    this.RaisePropertyChanged("ReceiverLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string ReceiverCountry {
            get {
                return this.ReceiverCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverCountryField, value) != true)) {
                    this.ReceiverCountryField = value;
                    this.RaisePropertyChanged("ReceiverCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=13)]
        public string ReceiverCity {
            get {
                return this.ReceiverCityField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverCityField, value) != true)) {
                    this.ReceiverCityField = value;
                    this.RaisePropertyChanged("ReceiverCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string ReceiverAdressLine1 {
            get {
                return this.ReceiverAdressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAdressLine1Field, value) != true)) {
                    this.ReceiverAdressLine1Field = value;
                    this.RaisePropertyChanged("ReceiverAdressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=15)]
        public string ReceiverAdressLine2 {
            get {
                return this.ReceiverAdressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverAdressLine2Field, value) != true)) {
                    this.ReceiverAdressLine2Field = value;
                    this.RaisePropertyChanged("ReceiverAdressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=16)]
        public string ReceiverPhone1 {
            get {
                return this.ReceiverPhone1Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverPhone1Field, value) != true)) {
                    this.ReceiverPhone1Field = value;
                    this.RaisePropertyChanged("ReceiverPhone1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=17)]
        public string ReceiverPhone2 {
            get {
                return this.ReceiverPhone2Field;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverPhone2Field, value) != true)) {
                    this.ReceiverPhone2Field = value;
                    this.RaisePropertyChanged("ReceiverPhone2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=18)]
        public TransFastWCF.TransFastWebService.DocumentData ReceiverDocument {
            get {
                return this.ReceiverDocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverDocumentField, value) != true)) {
                    this.ReceiverDocumentField = value;
                    this.RaisePropertyChanged("ReceiverDocument");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=19)]
        public System.DateTime ReceiverDOB {
            get {
                return this.ReceiverDOBField;
            }
            set {
                if ((this.ReceiverDOBField.Equals(value) != true)) {
                    this.ReceiverDOBField = value;
                    this.RaisePropertyChanged("ReceiverDOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=20)]
        public TransFastWCF.TransFastWebService.BankAccout BankAccount {
            get {
                return this.BankAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAccountField, value) != true)) {
                    this.BankAccountField = value;
                    this.RaisePropertyChanged("BankAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=21)]
        public TransFastWCF.TransFastWebService.ModeOfPayment PaymentMethod {
            get {
                return this.PaymentMethodField;
            }
            set {
                if ((this.PaymentMethodField.Equals(value) != true)) {
                    this.PaymentMethodField = value;
                    this.RaisePropertyChanged("PaymentMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=22)]
        public int InvoiceConsecutive {
            get {
                return this.InvoiceConsecutiveField;
            }
            set {
                if ((this.InvoiceConsecutiveField.Equals(value) != true)) {
                    this.InvoiceConsecutiveField = value;
                    this.RaisePropertyChanged("InvoiceConsecutive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=23)]
        public string InvoicePin {
            get {
                return this.InvoicePinField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicePinField, value) != true)) {
                    this.InvoicePinField = value;
                    this.RaisePropertyChanged("InvoicePin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=24)]
        public int InvoiceInternalID {
            get {
                return this.InvoiceInternalIDField;
            }
            set {
                if ((this.InvoiceInternalIDField.Equals(value) != true)) {
                    this.InvoiceInternalIDField = value;
                    this.RaisePropertyChanged("InvoiceInternalID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=25)]
        public string InvoiceMessage {
            get {
                return this.InvoiceMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceMessageField, value) != true)) {
                    this.InvoiceMessageField = value;
                    this.RaisePropertyChanged("InvoiceMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=26)]
        public double InvoiceAmmountToReceive {
            get {
                return this.InvoiceAmmountToReceiveField;
            }
            set {
                if ((this.InvoiceAmmountToReceiveField.Equals(value) != true)) {
                    this.InvoiceAmmountToReceiveField = value;
                    this.RaisePropertyChanged("InvoiceAmmountToReceive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=27)]
        public string InvoiceCurrency {
            get {
                return this.InvoiceCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceCurrencyField, value) != true)) {
                    this.InvoiceCurrencyField = value;
                    this.RaisePropertyChanged("InvoiceCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=28)]
        public string InvoiceExchangeRate {
            get {
                return this.InvoiceExchangeRateField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceExchangeRateField, value) != true)) {
                    this.InvoiceExchangeRateField = value;
                    this.RaisePropertyChanged("InvoiceExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=29)]
        public bool ReadyForPay {
            get {
                return this.ReadyForPayField;
            }
            set {
                if ((this.ReadyForPayField.Equals(value) != true)) {
                    this.ReadyForPayField = value;
                    this.RaisePropertyChanged("ReadyForPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=30)]
        public TransFastWCF.TransFastWebService.InvoiceStatus InvoiceStatus {
            get {
                return this.InvoiceStatusField;
            }
            set {
                if ((this.InvoiceStatusField.Equals(value) != true)) {
                    this.InvoiceStatusField = value;
                    this.RaisePropertyChanged("InvoiceStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=31)]
        public TransFastWCF.TransFastWebService.AditionalData InvoiceAditionalData {
            get {
                return this.InvoiceAditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceAditionalDataField, value) != true)) {
                    this.InvoiceAditionalDataField = value;
                    this.RaisePropertyChanged("InvoiceAditionalData");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnResult", Namespace="http://www.legionelite.com/")]
    public enum ReturnResult1 : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ok = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HasError = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoData = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentData", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class DocumentData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TransFastWCF.TransFastWebService.DocumentType TypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        private System.DateTime EmissionDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmissorField;
        
        private System.DateTime ExpirationDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TransFastWCF.TransFastWebService.DocumentType Type {
            get {
                return this.TypeField;
            }
            set {
                if ((this.TypeField.Equals(value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime EmissionDate {
            get {
                return this.EmissionDateField;
            }
            set {
                if ((this.EmissionDateField.Equals(value) != true)) {
                    this.EmissionDateField = value;
                    this.RaisePropertyChanged("EmissionDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Emissor {
            get {
                return this.EmissorField;
            }
            set {
                if ((object.ReferenceEquals(this.EmissorField, value) != true)) {
                    this.EmissorField = value;
                    this.RaisePropertyChanged("Emissor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime ExpirationDate {
            get {
                return this.ExpirationDateField;
            }
            set {
                if ((this.ExpirationDateField.Equals(value) != true)) {
                    this.ExpirationDateField = value;
                    this.RaisePropertyChanged("ExpirationDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BankAccout", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class BankAccout : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCityField;
        
        private TransFastWCF.TransFastWebService.AccountType AccountTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BranchCity {
            get {
                return this.BranchCityField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCityField, value) != true)) {
                    this.BranchCityField = value;
                    this.RaisePropertyChanged("BranchCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public TransFastWCF.TransFastWebService.AccountType AccountType {
            get {
                return this.AccountTypeField;
            }
            set {
                if ((this.AccountTypeField.Equals(value) != true)) {
                    this.AccountTypeField = value;
                    this.RaisePropertyChanged("AccountType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string BankCode {
            get {
                return this.BankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCodeField, value) != true)) {
                    this.BankCodeField = value;
                    this.RaisePropertyChanged("BankCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AditionalData", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class AditionalData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double ExchangeRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountCurrencyField;
        
        private double AmmountDueField;
        
        private double ComissionDueField;
        
        private System.DateTime AvaliableDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double ExchangeRate {
            get {
                return this.ExchangeRateField;
            }
            set {
                if ((this.ExchangeRateField.Equals(value) != true)) {
                    this.ExchangeRateField = value;
                    this.RaisePropertyChanged("ExchangeRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AccountCurrency {
            get {
                return this.AccountCurrencyField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountCurrencyField, value) != true)) {
                    this.AccountCurrencyField = value;
                    this.RaisePropertyChanged("AccountCurrency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double AmmountDue {
            get {
                return this.AmmountDueField;
            }
            set {
                if ((this.AmmountDueField.Equals(value) != true)) {
                    this.AmmountDueField = value;
                    this.RaisePropertyChanged("AmmountDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double ComissionDue {
            get {
                return this.ComissionDueField;
            }
            set {
                if ((this.ComissionDueField.Equals(value) != true)) {
                    this.ComissionDueField = value;
                    this.RaisePropertyChanged("ComissionDue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime AvaliableDate {
            get {
                return this.AvaliableDateField;
            }
            set {
                if ((this.AvaliableDateField.Equals(value) != true)) {
                    this.AvaliableDateField = value;
                    this.RaisePropertyChanged("AvaliableDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sex", Namespace="http://www.legionelite.com/")]
    public enum Sex : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        M = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        F = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        N = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModeOfPayment", Namespace="http://www.legionelite.com/")]
    public enum ModeOfPayment : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BankDeposit = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PickUp = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HomeDelivery = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceStatus", Namespace="http://www.legionelite.com/")]
    public enum InvoiceStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DELETED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UNVALIDATED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OUTSTANDING_SEND = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRANSMITTION_PROCESS = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ON_HOLD_AT_ADMINISTRATION = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ON_HOLD_AT_TRANSMISSION = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEND = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WITH_INCIDENTS = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELLED = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELLATION_BILLING = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAID = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IS_REQUIERED_AUTORIZATION_BC = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IS_REQUIERED_AUTORIZATION_DB = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LOCKED_IN_ADMINISTRATION = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CANCELLATION_REQUEST = 15,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentType", Namespace="http://www.legionelite.com/")]
    public enum DocumentType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OTH = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAS = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RES = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DNI = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUI = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CED = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DRV = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NONE = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AccountType", Namespace="http://www.legionelite.com/")]
    public enum AccountType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Savings = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Current = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Others = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MTO_PayoutRequest", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class MTO_PayoutRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POSCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTermField;
        
        private TransFastWCF.TransFastWebService.SearchPayMode SearchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverFullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReceiverDocumentNumberField;
        
        private double AmmountToPayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrencyToPayField;
        
        private System.DateTime PaymentDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string POSCode {
            get {
                return this.POSCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.POSCodeField, value) != true)) {
                    this.POSCodeField = value;
                    this.RaisePropertyChanged("POSCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SearchTerm {
            get {
                return this.SearchTermField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTermField, value) != true)) {
                    this.SearchTermField = value;
                    this.RaisePropertyChanged("SearchTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public TransFastWCF.TransFastWebService.SearchPayMode SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((this.SearchTypeField.Equals(value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReceiverFullName {
            get {
                return this.ReceiverFullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverFullNameField, value) != true)) {
                    this.ReceiverFullNameField = value;
                    this.RaisePropertyChanged("ReceiverFullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string ReceiverDocumentNumber {
            get {
                return this.ReceiverDocumentNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ReceiverDocumentNumberField, value) != true)) {
                    this.ReceiverDocumentNumberField = value;
                    this.RaisePropertyChanged("ReceiverDocumentNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double AmmountToPay {
            get {
                return this.AmmountToPayField;
            }
            set {
                if ((this.AmmountToPayField.Equals(value) != true)) {
                    this.AmmountToPayField = value;
                    this.RaisePropertyChanged("AmmountToPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CurrencyToPay {
            get {
                return this.CurrencyToPayField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrencyToPayField, value) != true)) {
                    this.CurrencyToPayField = value;
                    this.RaisePropertyChanged("CurrencyToPay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime PaymentDate {
            get {
                return this.PaymentDateField;
            }
            set {
                if ((this.PaymentDateField.Equals(value) != true)) {
                    this.PaymentDateField = value;
                    this.RaisePropertyChanged("PaymentDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MTO_PayoutResponse", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class MTO_PayoutResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TransFastWCF.TransFastWebService.ReturnResult1 ReturnResultField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PaymentTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TransFastWCF.TransFastWebService.ReturnResult1 ReturnResult {
            get {
                return this.ReturnResultField;
            }
            set {
                if ((this.ReturnResultField.Equals(value) != true)) {
                    this.ReturnResultField = value;
                    this.RaisePropertyChanged("ReturnResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReturnDescription {
            get {
                return this.ReturnDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDescriptionField, value) != true)) {
                    this.ReturnDescriptionField = value;
                    this.RaisePropertyChanged("ReturnDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PaymentToken {
            get {
                return this.PaymentTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.PaymentTokenField, value) != true)) {
                    this.PaymentTokenField = value;
                    this.RaisePropertyChanged("PaymentToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MTO_ConfirmRequest", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class MTO_ConfirmRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserTokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POSCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SearchTermField;
        
        private TransFastWCF.TransFastWebService.SearchPayMode SearchTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string UserToken {
            get {
                return this.UserTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.UserTokenField, value) != true)) {
                    this.UserTokenField = value;
                    this.RaisePropertyChanged("UserToken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string POSCode {
            get {
                return this.POSCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.POSCodeField, value) != true)) {
                    this.POSCodeField = value;
                    this.RaisePropertyChanged("POSCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SearchTerm {
            get {
                return this.SearchTermField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchTermField, value) != true)) {
                    this.SearchTermField = value;
                    this.RaisePropertyChanged("SearchTerm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public TransFastWCF.TransFastWebService.SearchPayMode SearchType {
            get {
                return this.SearchTypeField;
            }
            set {
                if ((this.SearchTypeField.Equals(value) != true)) {
                    this.SearchTypeField = value;
                    this.RaisePropertyChanged("SearchType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MTO_COnfirmResponse", Namespace="http://www.legionelite.com/")]
    [System.SerializableAttribute()]
    public partial class MTO_COnfirmResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private TransFastWCF.TransFastWebService.ReturnResult1 ReturnResultField;
        
        private int ReturnCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReturnDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TransFastWCF.TransFastWebService.ReturnResult1 ReturnResult {
            get {
                return this.ReturnResultField;
            }
            set {
                if ((this.ReturnResultField.Equals(value) != true)) {
                    this.ReturnResultField = value;
                    this.RaisePropertyChanged("ReturnResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int ReturnCode {
            get {
                return this.ReturnCodeField;
            }
            set {
                if ((this.ReturnCodeField.Equals(value) != true)) {
                    this.ReturnCodeField = value;
                    this.RaisePropertyChanged("ReturnCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ReturnDescription {
            get {
                return this.ReturnDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReturnDescriptionField, value) != true)) {
                    this.ReturnDescriptionField = value;
                    this.RaisePropertyChanged("ReturnDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="COM", ConfigurationName="TransFastWebService.MTTOCORRESPONDENTTKSoap")]
    public interface MTTOCORRESPONDENTTKSoap {
        
        // CODEGEN: Generating message contract since element name Q from namespace COM is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="COM/Step0UserAuthenticate", ReplyAction="*")]
        TransFastWCF.TransFastWebService.Step0UserAuthenticateResponse Step0UserAuthenticate(TransFastWCF.TransFastWebService.Step0UserAuthenticateRequest request);
        
        // CODEGEN: Generating message contract since element name Q from namespace COM is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="COM/Step1SearchMT", ReplyAction="*")]
        TransFastWCF.TransFastWebService.Step1SearchMTResponse Step1SearchMT(TransFastWCF.TransFastWebService.Step1SearchMTRequest request);
        
        // CODEGEN: Generating message contract since element name Q from namespace COM is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="COM/Step2PayoutMT", ReplyAction="*")]
        TransFastWCF.TransFastWebService.Step2PayoutMTResponse Step2PayoutMT(TransFastWCF.TransFastWebService.Step2PayoutMTRequest request);
        
        // CODEGEN: Generating message contract since element name Q from namespace COM is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="COM/Step3ConfirmMT", ReplyAction="*")]
        TransFastWCF.TransFastWebService.Step3ConfirmMTResponse Step3ConfirmMT(TransFastWCF.TransFastWebService.Step3ConfirmMTRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step0UserAuthenticateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step0UserAuthenticate", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step0UserAuthenticateRequestBody Body;
        
        public Step0UserAuthenticateRequest() {
        }
        
        public Step0UserAuthenticateRequest(TransFastWCF.TransFastWebService.Step0UserAuthenticateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step0UserAuthenticateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.EntityAuth Q;
        
        public Step0UserAuthenticateRequestBody() {
        }
        
        public Step0UserAuthenticateRequestBody(TransFastWCF.TransFastWebService.EntityAuth Q) {
            this.Q = Q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step0UserAuthenticateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step0UserAuthenticateResponse", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step0UserAuthenticateResponseBody Body;
        
        public Step0UserAuthenticateResponse() {
        }
        
        public Step0UserAuthenticateResponse(TransFastWCF.TransFastWebService.Step0UserAuthenticateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step0UserAuthenticateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.AutorizationResponse Step0UserAuthenticateResult;
        
        public Step0UserAuthenticateResponseBody() {
        }
        
        public Step0UserAuthenticateResponseBody(TransFastWCF.TransFastWebService.AutorizationResponse Step0UserAuthenticateResult) {
            this.Step0UserAuthenticateResult = Step0UserAuthenticateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step1SearchMTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step1SearchMT", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step1SearchMTRequestBody Body;
        
        public Step1SearchMTRequest() {
        }
        
        public Step1SearchMTRequest(TransFastWCF.TransFastWebService.Step1SearchMTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step1SearchMTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.MTO_InfoRequest Q;
        
        public Step1SearchMTRequestBody() {
        }
        
        public Step1SearchMTRequestBody(TransFastWCF.TransFastWebService.MTO_InfoRequest Q) {
            this.Q = Q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step1SearchMTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step1SearchMTResponse", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step1SearchMTResponseBody Body;
        
        public Step1SearchMTResponse() {
        }
        
        public Step1SearchMTResponse(TransFastWCF.TransFastWebService.Step1SearchMTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step1SearchMTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.MTO_InfoResponse Step1SearchMTResult;
        
        public Step1SearchMTResponseBody() {
        }
        
        public Step1SearchMTResponseBody(TransFastWCF.TransFastWebService.MTO_InfoResponse Step1SearchMTResult) {
            this.Step1SearchMTResult = Step1SearchMTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step2PayoutMTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step2PayoutMT", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step2PayoutMTRequestBody Body;
        
        public Step2PayoutMTRequest() {
        }
        
        public Step2PayoutMTRequest(TransFastWCF.TransFastWebService.Step2PayoutMTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step2PayoutMTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.MTO_PayoutRequest Q;
        
        public Step2PayoutMTRequestBody() {
        }
        
        public Step2PayoutMTRequestBody(TransFastWCF.TransFastWebService.MTO_PayoutRequest Q) {
            this.Q = Q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step2PayoutMTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step2PayoutMTResponse", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step2PayoutMTResponseBody Body;
        
        public Step2PayoutMTResponse() {
        }
        
        public Step2PayoutMTResponse(TransFastWCF.TransFastWebService.Step2PayoutMTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step2PayoutMTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.MTO_PayoutResponse Step2PayoutMTResult;
        
        public Step2PayoutMTResponseBody() {
        }
        
        public Step2PayoutMTResponseBody(TransFastWCF.TransFastWebService.MTO_PayoutResponse Step2PayoutMTResult) {
            this.Step2PayoutMTResult = Step2PayoutMTResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step3ConfirmMTRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step3ConfirmMT", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step3ConfirmMTRequestBody Body;
        
        public Step3ConfirmMTRequest() {
        }
        
        public Step3ConfirmMTRequest(TransFastWCF.TransFastWebService.Step3ConfirmMTRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step3ConfirmMTRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.MTO_ConfirmRequest Q;
        
        public Step3ConfirmMTRequestBody() {
        }
        
        public Step3ConfirmMTRequestBody(TransFastWCF.TransFastWebService.MTO_ConfirmRequest Q) {
            this.Q = Q;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Step3ConfirmMTResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Step3ConfirmMTResponse", Namespace="COM", Order=0)]
        public TransFastWCF.TransFastWebService.Step3ConfirmMTResponseBody Body;
        
        public Step3ConfirmMTResponse() {
        }
        
        public Step3ConfirmMTResponse(TransFastWCF.TransFastWebService.Step3ConfirmMTResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="COM")]
    public partial class Step3ConfirmMTResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TransFastWCF.TransFastWebService.MTO_COnfirmResponse Step3ConfirmMTResult;
        
        public Step3ConfirmMTResponseBody() {
        }
        
        public Step3ConfirmMTResponseBody(TransFastWCF.TransFastWebService.MTO_COnfirmResponse Step3ConfirmMTResult) {
            this.Step3ConfirmMTResult = Step3ConfirmMTResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MTTOCORRESPONDENTTKSoapChannel : TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MTTOCORRESPONDENTTKSoapClient : System.ServiceModel.ClientBase<TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap>, TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap {
        
        public MTTOCORRESPONDENTTKSoapClient() {
        }
        
        public MTTOCORRESPONDENTTKSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MTTOCORRESPONDENTTKSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTTOCORRESPONDENTTKSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MTTOCORRESPONDENTTKSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransFastWCF.TransFastWebService.Step0UserAuthenticateResponse TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap.Step0UserAuthenticate(TransFastWCF.TransFastWebService.Step0UserAuthenticateRequest request) {
            return base.Channel.Step0UserAuthenticate(request);
        }
        
        public TransFastWCF.TransFastWebService.AutorizationResponse Step0UserAuthenticate(TransFastWCF.TransFastWebService.EntityAuth Q) {
            TransFastWCF.TransFastWebService.Step0UserAuthenticateRequest inValue = new TransFastWCF.TransFastWebService.Step0UserAuthenticateRequest();
            inValue.Body = new TransFastWCF.TransFastWebService.Step0UserAuthenticateRequestBody();
            inValue.Body.Q = Q;
            TransFastWCF.TransFastWebService.Step0UserAuthenticateResponse retVal = ((TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap)(this)).Step0UserAuthenticate(inValue);
            return retVal.Body.Step0UserAuthenticateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransFastWCF.TransFastWebService.Step1SearchMTResponse TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap.Step1SearchMT(TransFastWCF.TransFastWebService.Step1SearchMTRequest request) {
            return base.Channel.Step1SearchMT(request);
        }
        
        public TransFastWCF.TransFastWebService.MTO_InfoResponse Step1SearchMT(TransFastWCF.TransFastWebService.MTO_InfoRequest Q) {
            TransFastWCF.TransFastWebService.Step1SearchMTRequest inValue = new TransFastWCF.TransFastWebService.Step1SearchMTRequest();
            inValue.Body = new TransFastWCF.TransFastWebService.Step1SearchMTRequestBody();
            inValue.Body.Q = Q;
            TransFastWCF.TransFastWebService.Step1SearchMTResponse retVal = ((TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap)(this)).Step1SearchMT(inValue);
            return retVal.Body.Step1SearchMTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransFastWCF.TransFastWebService.Step2PayoutMTResponse TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap.Step2PayoutMT(TransFastWCF.TransFastWebService.Step2PayoutMTRequest request) {
            return base.Channel.Step2PayoutMT(request);
        }
        
        public TransFastWCF.TransFastWebService.MTO_PayoutResponse Step2PayoutMT(TransFastWCF.TransFastWebService.MTO_PayoutRequest Q) {
            TransFastWCF.TransFastWebService.Step2PayoutMTRequest inValue = new TransFastWCF.TransFastWebService.Step2PayoutMTRequest();
            inValue.Body = new TransFastWCF.TransFastWebService.Step2PayoutMTRequestBody();
            inValue.Body.Q = Q;
            TransFastWCF.TransFastWebService.Step2PayoutMTResponse retVal = ((TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap)(this)).Step2PayoutMT(inValue);
            return retVal.Body.Step2PayoutMTResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TransFastWCF.TransFastWebService.Step3ConfirmMTResponse TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap.Step3ConfirmMT(TransFastWCF.TransFastWebService.Step3ConfirmMTRequest request) {
            return base.Channel.Step3ConfirmMT(request);
        }
        
        public TransFastWCF.TransFastWebService.MTO_COnfirmResponse Step3ConfirmMT(TransFastWCF.TransFastWebService.MTO_ConfirmRequest Q) {
            TransFastWCF.TransFastWebService.Step3ConfirmMTRequest inValue = new TransFastWCF.TransFastWebService.Step3ConfirmMTRequest();
            inValue.Body = new TransFastWCF.TransFastWebService.Step3ConfirmMTRequestBody();
            inValue.Body.Q = Q;
            TransFastWCF.TransFastWebService.Step3ConfirmMTResponse retVal = ((TransFastWCF.TransFastWebService.MTTOCORRESPONDENTTKSoap)(this)).Step3ConfirmMT(inValue);
            return retVal.Body.Step3ConfirmMTResult;
        }
    }
}
